use crate::storage::Language;

/// Small, dependency-free UI dictionary. Savegame data and resource names stay
/// in their game-provided form; only application chrome and explanatory text
/// are translated here.
pub fn text(language: Language, key: &str) -> &'static str {
    let (english, german, french, spanish) = match key {
        "ready" => ("Ready", "Bereit", "Prêt", "Listo"),
        "save_stored" => ("New savegame stored", "Neues Savegame gespeichert", "Nouvelle sauvegarde enregistrée", "Nueva partida guardada"),
        "no_changes" => ("No changes found", "Keine Änderungen gefunden", "Aucune modification trouvée", "No se encontraron cambios"),
        "analyzing_save" => ("Analyzing savegame …", "Savegame wird analysiert …", "Analyse de la sauvegarde …", "Analizando partida …"),
        "save_analyzed" => ("Savegame analyzed", "Savegame analysiert", "Sauvegarde analysée", "Partida analizada"),
        "analysis_failed" => ("Savegame could not be analyzed", "Savegame konnte nicht analysiert werden", "Impossible d'analyser la sauvegarde", "No se pudo analizar la partida"),
        "analysis_stopped" => ("Savegame analysis stopped", "Savegame-Analyse wurde beendet", "Analyse de la sauvegarde arrêtée", "Análisis de partida detenido"),
        "save_updated" => ("Savegame updated", "Savegame aktualisiert", "Sauvegarde mise à jour", "Partida actualizada"),
        "node_data_saved" => ("Node data saved", "Node-Daten gespeichert", "Données des nodes enregistrées", "Datos de nodos guardados"),
        "initialization_failed" => (
            "Initialization failed",
            "Initialisierung fehlgeschlagen",
            "Échec de l'initialisation",
            "Error de inicialización",
        ),
        "upload_save" => ("＋  Upload savegame", "＋  Savegame hochladen", "＋  Charger une sauvegarde", "＋  Cargar partida"),
        "refresh" => ("↻  Refresh", "↻  Refresh", "↻  Actualiser", "↻  Actualizar"),
        "remove_save" => ("✕  Remove savegame", "✕  Savegame entfernen", "✕  Retirer la sauvegarde", "✕  Quitar partida"),
        "settings" => ("Settings", "Einstellungen", "Paramètres", "Ajustes"),
        "language" => ("Language", "Sprache", "Langue", "Idioma"),
        "node_names" => ("Show node names", "Node-Namen anzeigen", "Afficher les noms des nodes", "Mostrar nombres de nodos"),
        "debug_mode" => ("Debug mode", "Debug-Modus", "Mode débogage", "Modo de depuración"),
        "pause_background" => ("Do not render map when unfocused", "Map bei Alt-Tab nicht rendern", "Ne pas afficher la carte en arrière-plan", "No renderizar el mapa en segundo plano"),
        "rails_wip" => ("Show rails", "Rails anzeigen", "Afficher les rails", "Mostrar raíles"),
        "show_foundations" => ("Show foundations", "Foundations anzeigen", "Afficher les fondations", "Mostrar cimientos"),
        "show_belts" => ("Show belts", "Belts anzeigen", "Mostrar les convoyeurs", "Mostrar cintas"),
        "node_size" => ("Node size", "Node-Größe", "Taille des nodes", "Tamaño de los nodos"),
        "background_throttle" => ("Rendering is automatically throttled in the background.", "Im Hintergrund wird die Darstellung automatisch gedrosselt.", "Le rendu est automatiquement limité en arrière-plan.", "El renderizado se ralentiza automáticamente en segundo plano."),
        "map_panel" => ("Map panel", "Map-Panel", "Panneau de carte", "Panel del mapa"),
        "panel_open_hint" => ("Move the cursor to the right edge to open.", "Zum Öffnen den Cursor an den rechten Fensterrand bewegen.", "Placez le curseur sur le bord droit pour ouvrir.", "Mueve el cursor al borde derecho para abrirlo."),
        "close_panel" => ("×  Close panel", "×  Panel schließen", "×  Fermer le panneau", "×  Cerrar panel"),
        "resource_nodes" => ("Resource nodes", "Resource-Nodes", "Nodes de ressources", "Nodos de recursos"),
        "nodes" => ("nodes", "Nodes", "nodes", "nodos"),
        "nodes_loaded" => ("nodes loaded", "Nodes geladen", "nodes chargés", "nodos cargados"),
        "visible_nodes" => ("visible nodes", "sichtbare Nodes", "nodes visibles", "nodos visibles"),
        "remaining_short" => ("remaining", "übrig", "restantes", "restantes"),
        "zoom" => ("Zoom", "Zoom", "Zoom", "Zoom"),
        "cursor_world" => ("Cursor · World", "Cursor · Welt", "Curseur · Monde", "Cursor · Mundo"),
        "rails" => ("rails", "Schienen", "rails", "raíles"),
        "foundation_count" => ("foundations", "Foundations", "fondations", "cimientos"),
        "belt_count" => ("belts", "Belts", "convoyeurs", "cintas"),
        "belts" => ("belts", "Belts", "convoyeurs", "cintas"),
        "claimed_nodes" => ("claimed nodes", "geclaimte Nodes", "nodes revendiqués", "nodos reclamados"),
        "belts_laid" => ("Belts laid", "Belts verlegt", "Convoyeurs posés", "Cintas instaladas"),
        "rails_laid" => ("Rails laid", "Schienen verlegt", "Rails posés", "Raíles instalados"),
        "playtime" => ("Playtime", "Spielzeit", "Temps de jeu", "Tiempo de juego"),
        "max_unclaimed" => ("Maximum capacity of unclaimed nodes", "Maximale Kapazität unclaimed Nodes", "Capacité maximale des nodes non revendiqués", "Capacidad máxima de nodos sin reclamar"),
        "unclaimed_hint" => ("Unclaimed nodes use the selected miner at the maximum 250% clock.", "Unclaimed werden mit dem gewählten Miner bei maximal 250% berechnet.", "Les nodes non revendiqués utilisent le mineur choisi à 250% maximum.", "Los nodos sin reclamar usan el minero seleccionado al 250% máximo."),
        "panel_resize_hint" => ("Drag the left edge to resize. Push it to the right edge to close.", "Panelbreite durch Ziehen der linken Kante ändern. Ganz nach rechts zusammenschieben schließt es.", "Tirez le bord gauche pour redimensionner. Repoussez-le vers le bord droit pour fermer.", "Arrastra el borde izquierdo para cambiar el tamaño. Llévalo al borde derecho para cerrarlo."),
        "app_title" => ("Satisfactory Map Tracker", "Satisfactory Map Tracker", "Satisfactory Map Tracker", "Satisfactory Map Tracker"),
        "draw_rectangle" => ("▭  Draw rectangle", "▭  Rechteck zeichnen", "▭  Dessiner un rectangle", "▭  Dibujar rectángulo"),
        "cancel_rectangle" => ("×  Cancel drawing", "×  Zeichnen abbrechen", "×  Annuler le dessin", "×  Cancelar dibujo"),
        "draw_circle" => ("○  Draw circle", "○  Kreis zeichnen", "○  Dessiner un cercle", "○  Dibujar círculo"),
        "cancel_circle" => ("×  Cancel circle", "×  Kreis abbrechen", "×  Annuler le cercle", "×  Cancelar círculo"),
        "draw_arrow" => ("➜  Draw arrow", "➜  Pfeil zeichnen", "➜  Dessiner une flèche", "➜  Dibujar flecha"),
        "cancel_arrow" => ("×  Cancel arrow", "×  Pfeil abbrechen", "×  Annuler la flèche", "×  Cancelar flecha"),
        "draw_text" => ("T  Add text", "T  Text hinzufügen", "T  Ajouter du texte", "T  Añadir texto"),
        "cancel_text" => ("×  Cancel text", "×  Text abbrechen", "×  Annuler le texte", "×  Cancelar texto"),
        "text_label" => ("Text", "Text", "Texte", "Texto"),
        "save_text" => ("Save", "Speichern", "Enregistrer", "Guardar"),
        "cancel_text_edit" => ("Cancel", "Abbrechen", "Annuler", "Cancelar"),
        "rectangle" => ("Rectangle", "Rechteck", "Rectangle", "Rectángulo"),
        "circle" => ("Circle", "Kreis", "Cercle", "Círculo"),
        "arrow" => ("Arrow", "Pfeil", "Flèche", "Flecha"),
        "delete_annotation" => ("Delete drawing", "Zeichnung löschen", "Supprimer le dessin", "Eliminar dibujo"),
        "move_rectangle" => ("Move", "Verschieben", "Déplacer", "Mover"),
        "delete_rectangle" => ("Delete", "Löschen", "Supprimer", "Eliminar"),
        "error" => ("Error", "Fehler", "Erreur", "Error"),
        "not_initialized" => ("The application could not be initialized.", "Die Anwendung konnte nicht initialisiert werden.", "L'application n'a pas pu être initialisée.", "No se pudo inicializar la aplicación."),
        "no_save" => ("No Satisfactory savegame selected.", "Kein Satisfactory-Savegame ausgewählt.", "Aucune sauvegarde Satisfactory sélectionnée.", "No hay ninguna partida de Satisfactory seleccionada."),
        "upload_hint" => ("Please upload a savegame above.", "Bitte oben ein Savegame hochladen.", "Chargez une sauvegarde ci-dessus.", "Carga una partida arriba."),
        "map_paused" => ("Map rendering is paused while the window is in the background.", "Karten-Rendering pausiert, solange das Fenster im Hintergrund ist.", "Le rendu de la carte est en pause lorsque la fenêtre est en arrière-plan.", "El renderizado del mapa está pausado cuando la ventana está en segundo plano."),
        "change_in_settings" => ("(Can be changed in Settings)", "(In den Einstellungen änderbar)", "(Modifiable dans les paramètres)", "(Se puede cambiar en Ajustes)"),
        "save_status" => ("Savegame status", "Savegame-Status", "État de la sauvegarde", "Estado de la partida"),
        "no_saved_save" => ("No savegame stored yet.", "Noch kein Savegame gespeichert.", "Aucune sauvegarde enregistrée.", "Todavía no hay ninguna partida guardada."),
        "local_copy" => ("Local copy", "Lokale Kopie", "Copie locale", "Copia local"),
        "resource_remaining" => ("Resources remaining", "Ressourcen übrig", "Ressources restantes", "Recursos restantes"),
        "no_extractors" => ("No placed extractor data loaded yet.", "Noch keine platzierten Extractor-Daten geladen.", "Aucune donnée d'extracteur placé n'est encore chargée.", "Aún no se han cargado extractores colocados."),
        "available_per_minute" => ("available per minute", "pro Minute verfügbar", "disponibles par minute", "disponibles por minuto"),
        "not_fully_used" => ("not fully used", "nicht vollständig genutzt", "non utilisés complètement", "no utilizados por completo"),
        "resource" => ("Resource", "Ressource", "Ressource", "Recurso"),
        "purity" => ("Purity", "Reinheit", "Pureté", "Pureza"),
        "all_resources" => ("All resources", "Alle Ressourcen", "Toutes les ressources", "Todos los recursos"),
        "all_purities" => ("All purities", "Alle Reinheiten", "Toutes les puretés", "Todas las purezas"),
        "claimed_only" => ("Claimed nodes only", "Nur geclaimte Nodes", "Nodes revendiqués uniquement", "Solo nodos reclamados"),
        "partial_only" => ("Partially used nodes only", "Nur nicht vollständig genutzte Nodes", "Nodes partiellement utilisés uniquement", "Solo nodos parcialmente usados"),
        "grid" => ("Show coordinate grid", "Koordinatenraster anzeigen", "Afficher la grille de coordonnées", "Mostrar cuadrícula de coordenadas"),
        "world_data_hint" => ("The map and positions come from local world data.", "Karte und Positionen stammen aus den lokalen Welt-Daten.", "La carte et les positions proviennent des données locales du monde.", "El mapa y las posiciones proceden de los datos locales del mundo."),
        "reset_view" => ("Reset view", "Ansicht zurücksetzen", "Réinitialiser la vue", "Restablecer vista"),
        "close" => ("Close", "Schließen", "Fermer", "Cerrar"),
        "usage" => ("Usage", "Ressourcenverbrauch", "Utilisation", "Uso"),
        "note" => ("Note", "Notiz", "Note", "Nota"),
        "yield" => ("Yield", "Ertrag", "Rendement", "Producción"),
        "theoretical_yield" => ("Theoretical miner yield", "Theoretischer Miner-Ertrag", "Rendement théorique du mineur", "Producción teórica del minero"),
        "maximum_settable" => ("Maximum settable", "Maximal einstellbar", "Maximum réglable", "Máximo configurable"),
        "powershards_clock" => ("Powershards", "Powershards", "Powershards", "Powershards"),
        "used_per_minute" => ("used per minute", "pro Minute verwendet", "utilisés par minute", "usados por minuto"),
        "free_per_minute" => ("Free", "Frei", "Libre", "Libre"),
        "occupancy" => ("Occupancy", "Belegung", "Occupation", "Ocupación"),
        "node_id" => ("Node ID", "Node-ID", "ID du node", "ID del nodo"),
        "world" => ("World", "Welt", "Monde", "Mundo"),
        "extractor_unknown" => ("Extractor not found in savegame", "Extractor keiner in der Save-Datei erkannt", "Extracteur introuvable dans la sauvegarde", "Extractor no encontrado en la partida"),
        "method" => ("Method", "Methode", "Méthode", "Método"),
        "rate_per_satellite" => ("Rate applies per resource-well satellite.", "Rate gilt pro Resource-Well-Satellit.", "Le débit s'applique par satellite du puits.", "La tasa se aplica por satélite del pozo."),
        "well_core" => ("Central resource-well core", "Zentraler Resource-Well-Kern", "Cœur central du puits de ressources", "Núcleo central del pozo de recursos"),
        "well_yield_hint" => ("Yield comes from the connected satellite nodes.", "Die Ausbeute kommt von den verbundenen Satelliten-Nodes.", "Le rendement vient des nodes satellites connectés.", "La producción procede de los nodos satélite conectados."),
        "manual_deposit" => ("Manual deposit – no miner extractor", "Manuelles Deposit – kein Miner-Extractor", "Gisement manuel – aucun extracteur", "Depósito manual – sin extractor minero"),
        "your_entry" => ("Your entry", "Dein Eintrag", "Votre saisie", "Tu entrada"),
        "satellite_usage" => ("Usage", "Nutzung", "Utilisation", "Uso"),
        "oil_extractor" => ("Oil Extractor", "Oil Extractor", "Extracteur de pétrole", "Extractor de petróleo"),
        "well_extractor" => ("Resource Well Extractor", "Resource Well Extractor", "Extracteur de puits de ressources", "Extractor de pozo de recursos"),
        "miner" => ("Miner", "Miner", "Mineur", "Minero"),
        "theoretical" => ("Theoretical", "Theoretischer", "Théorique", "Teórico"),
        "output" => ("Output", "Output", "Sortie", "Producción"),
        "satellites_total" => ("Total satellites", "Satelliten gesamt", "Total des satellites", "Satélites totales"),
        "satellites_in_well" => ("satellites in well", "Satelliten im Well", "satellites dans le puits", "satélites en el pozo"),
        "claimed" => ("●  Claimed", "●  Geclaimt", "●  Revendiqué", "●  Reclamado"),
        "unclaimed" => ("○  Unclaimed", "○  Nicht geclaimt", "○  Non revendiqué", "○  Sin reclamar"),
        _ => ("", "", "", ""),
    };

    match language {
        Language::English => english,
        Language::German => german,
        Language::French => french,
        Language::Spanish => spanish,
    }
}
